In [29]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [30]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [31]:
tokenizer.fit_on_texts(docs)

In [32]:
len(tokenizer.word_index)

17

In [33]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [34]:
from keras.utils import pad_sequences

sequences = pad_sequences(sequences, padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

In [39]:
model = Sequential()

model.add(Embedding(18, output_dim=2, input_length=5))
model.summary()

C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.compile('adam', 'accuracy')

In [41]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step
[[[-0.00450573 -0.01705507]
  [-0.04217302  0.02174319]
  [-0.00435042 -0.0399111 ]
  [-0.00435042 -0.0399111 ]
  [-0.00435042 -0.0399111 ]]

 [[-0.04217302  0.02174319]
  [-0.04217302  0.02174319]
  [-0.00435042 -0.0399111 ]
  [-0.00435042 -0.0399111 ]
  [-0.00435042 -0.0399111 ]]

 [[ 0.03532005 -0.0195837 ]
  [ 0.03532005 -0.0195837 ]
  [-0.00917088 -0.03126763]
  [-0.00435042 -0.0399111 ]
  [-0.00435042 -0.0399111 ]]

 [[-0.00027072 -0.00407658]
  [-0.04028834  0.04521627]
  [-0.00027072 -0.00407658]
  [-0.04217302  0.02174319]
  [-0.00027072 -0.00407658]]

 [[-0.04490203 -0.03830708]
  [ 0.00084875 -0.02149596]
  [ 0.04162521  0.03850952]
  [-0.01525204  0.03765359]
  [-0.00435042 -0.0399111 ]]

 [[-0.01127326 -0.02236003]
  [-0.01127326 -0.02236003]
  [-0.00435042 -0.0399111 ]
  [-0.00435042 -0.0399111 ]
  [-0.00435042 -0.0399111 ]]

 [[-0.01181128 -0.02252111]
  [-0.01181128 -0.02252111]
  [-0.00435042 -0.0399111 ]
  [-0.00435042 -0.0399111